// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Nom_Core = require("./Nom/Nom_Core.bs.js");
var Nom_Multi = require("./Nom/Nom_Multi.bs.js");
var Nom_Sequence = require("./Nom/Nom_Sequence.bs.js");

var Sequence = Nom_Sequence;

var Multi = Nom_Multi;

var Err = Nom_Core.Err;

var TransformException = Nom_Core.TransformException;

var identity = Nom_Core.identity;

var satisfy = Nom_Core.satisfy;

var satisfyN = Nom_Core.satisfyN;

var isEnd = Nom_Core.isEnd;

var $$return = Nom_Core.$$return;

var error = Nom_Core.error;

var mapValue = Nom_Core.mapValue;

var mapError = Nom_Core.mapError;

var map = Nom_Core.map;

var mapPassed = Nom_Core.mapPassed;

var mapFailed = Nom_Core.mapFailed;

var bind = Nom_Core.bind;

var or = Nom_Core.or;

var alt = Nom_Core.alt;

var cons = Nom_Core.cons;

var seq = Nom_Core.seq;

var listPrepend = Nom_Core.listPrepend;

var list = Nom_Core.list;

var tuple = Nom_Core.tuple;

var tuple3 = Nom_Core.tuple3;

var takeWhile = Nom_Core.takeWhile;

var takeWhile1 = Nom_Core.takeWhile1;

var reduceWhile = Nom_Core.reduceWhile;

var context = Nom_Core.context;

var contextMapError = Nom_Core.contextMapError;

var contextTuple = Nom_Core.contextTuple;

var contextTuple3 = Nom_Core.contextTuple3;

var allConsuming = Nom_Core.allConsuming;

var transform = Nom_Core.transform;

var transfromInPlace = Nom_Core.transfromInPlace;

exports.Err = Err;
exports.TransformException = TransformException;
exports.identity = identity;
exports.satisfy = satisfy;
exports.satisfyN = satisfyN;
exports.isEnd = isEnd;
exports.$$return = $$return;
exports.error = error;
exports.mapValue = mapValue;
exports.mapError = mapError;
exports.map = map;
exports.mapPassed = mapPassed;
exports.mapFailed = mapFailed;
exports.bind = bind;
exports.or = or;
exports.alt = alt;
exports.cons = cons;
exports.seq = seq;
exports.listPrepend = listPrepend;
exports.list = list;
exports.tuple = tuple;
exports.tuple3 = tuple3;
exports.takeWhile = takeWhile;
exports.takeWhile1 = takeWhile1;
exports.reduceWhile = reduceWhile;
exports.context = context;
exports.contextMapError = contextMapError;
exports.contextTuple = contextTuple;
exports.contextTuple3 = contextTuple3;
exports.allConsuming = allConsuming;
exports.transform = transform;
exports.transfromInPlace = transfromInPlace;
exports.Sequence = Sequence;
exports.Multi = Multi;
/* No side effect */
